// Code generated by protoc-gen-go. DO NOT EDIT.
// source: song.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BaseRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{0}
}
func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (dst *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(dst, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *BaseRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BaseResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{1}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *BaseResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SongChunk struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	RawBytes             []byte   `protobuf:"bytes,3,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	ChunkIndex           int32    `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Offset               int32    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int32    `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongChunk) Reset()         { *m = SongChunk{} }
func (m *SongChunk) String() string { return proto.CompactTextString(m) }
func (*SongChunk) ProtoMessage()    {}
func (*SongChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{2}
}
func (m *SongChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongChunk.Unmarshal(m, b)
}
func (m *SongChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongChunk.Marshal(b, m, deterministic)
}
func (dst *SongChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongChunk.Merge(dst, src)
}
func (m *SongChunk) XXX_Size() int {
	return xxx_messageInfo_SongChunk.Size(m)
}
func (m *SongChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_SongChunk.DiscardUnknown(m)
}

var xxx_messageInfo_SongChunk proto.InternalMessageInfo

func (m *SongChunk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SongChunk) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SongChunk) GetRawBytes() []byte {
	if m != nil {
		return m.RawBytes
	}
	return nil
}

func (m *SongChunk) GetChunkIndex() int32 {
	if m != nil {
		return m.ChunkIndex
	}
	return 0
}

func (m *SongChunk) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SongChunk) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SongChunkRequest struct {
	SongId               int32    `protobuf:"varint,2,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	ChunkIndex           int32    `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SongChunkRequest) Reset()         { *m = SongChunkRequest{} }
func (m *SongChunkRequest) String() string { return proto.CompactTextString(m) }
func (*SongChunkRequest) ProtoMessage()    {}
func (*SongChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{3}
}
func (m *SongChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongChunkRequest.Unmarshal(m, b)
}
func (m *SongChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongChunkRequest.Marshal(b, m, deterministic)
}
func (dst *SongChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongChunkRequest.Merge(dst, src)
}
func (m *SongChunkRequest) XXX_Size() int {
	return xxx_messageInfo_SongChunkRequest.Size(m)
}
func (m *SongChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SongChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SongChunkRequest proto.InternalMessageInfo

func (m *SongChunkRequest) GetSongId() int32 {
	if m != nil {
		return m.SongId
	}
	return 0
}

func (m *SongChunkRequest) GetChunkIndex() int32 {
	if m != nil {
		return m.ChunkIndex
	}
	return 0
}

type SongServerRequest struct {
	BaseRequest *BaseRequest `protobuf:"bytes,1,opt,name=base_request,json=baseRequest,proto3" json:"base_request,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*SongServerRequest_SongChunkRequest
	Request              isSongServerRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SongServerRequest) Reset()         { *m = SongServerRequest{} }
func (m *SongServerRequest) String() string { return proto.CompactTextString(m) }
func (*SongServerRequest) ProtoMessage()    {}
func (*SongServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{4}
}
func (m *SongServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongServerRequest.Unmarshal(m, b)
}
func (m *SongServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongServerRequest.Marshal(b, m, deterministic)
}
func (dst *SongServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongServerRequest.Merge(dst, src)
}
func (m *SongServerRequest) XXX_Size() int {
	return xxx_messageInfo_SongServerRequest.Size(m)
}
func (m *SongServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SongServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SongServerRequest proto.InternalMessageInfo

type isSongServerRequest_Request interface {
	isSongServerRequest_Request()
}

type SongServerRequest_SongChunkRequest struct {
	SongChunkRequest *SongChunkRequest `protobuf:"bytes,2,opt,name=song_chunk_request,json=songChunkRequest,proto3,oneof"`
}

func (*SongServerRequest_SongChunkRequest) isSongServerRequest_Request() {}

func (m *SongServerRequest) GetRequest() isSongServerRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SongServerRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *SongServerRequest) GetSongChunkRequest() *SongChunkRequest {
	if x, ok := m.GetRequest().(*SongServerRequest_SongChunkRequest); ok {
		return x.SongChunkRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SongServerRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SongServerRequest_OneofMarshaler, _SongServerRequest_OneofUnmarshaler, _SongServerRequest_OneofSizer, []interface{}{
		(*SongServerRequest_SongChunkRequest)(nil),
	}
}

func _SongServerRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SongServerRequest)
	// request
	switch x := m.Request.(type) {
	case *SongServerRequest_SongChunkRequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SongChunkRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SongServerRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _SongServerRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SongServerRequest)
	switch tag {
	case 2: // request.song_chunk_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SongChunkRequest)
		err := b.DecodeMessage(msg)
		m.Request = &SongServerRequest_SongChunkRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SongServerRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SongServerRequest)
	// request
	switch x := m.Request.(type) {
	case *SongServerRequest_SongChunkRequest:
		s := proto.Size(x.SongChunkRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SongChunkResponse struct {
	SongChunk            *SongChunk `protobuf:"bytes,1,opt,name=song_chunk,json=songChunk,proto3" json:"song_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SongChunkResponse) Reset()         { *m = SongChunkResponse{} }
func (m *SongChunkResponse) String() string { return proto.CompactTextString(m) }
func (*SongChunkResponse) ProtoMessage()    {}
func (*SongChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{5}
}
func (m *SongChunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongChunkResponse.Unmarshal(m, b)
}
func (m *SongChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongChunkResponse.Marshal(b, m, deterministic)
}
func (dst *SongChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongChunkResponse.Merge(dst, src)
}
func (m *SongChunkResponse) XXX_Size() int {
	return xxx_messageInfo_SongChunkResponse.Size(m)
}
func (m *SongChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SongChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SongChunkResponse proto.InternalMessageInfo

func (m *SongChunkResponse) GetSongChunk() *SongChunk {
	if m != nil {
		return m.SongChunk
	}
	return nil
}

type SongServerResponse struct {
	BaseResponse *BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*SongServerResponse_SongChunkResponse
	Response             isSongServerResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SongServerResponse) Reset()         { *m = SongServerResponse{} }
func (m *SongServerResponse) String() string { return proto.CompactTextString(m) }
func (*SongServerResponse) ProtoMessage()    {}
func (*SongServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{6}
}
func (m *SongServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SongServerResponse.Unmarshal(m, b)
}
func (m *SongServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SongServerResponse.Marshal(b, m, deterministic)
}
func (dst *SongServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SongServerResponse.Merge(dst, src)
}
func (m *SongServerResponse) XXX_Size() int {
	return xxx_messageInfo_SongServerResponse.Size(m)
}
func (m *SongServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SongServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SongServerResponse proto.InternalMessageInfo

type isSongServerResponse_Response interface {
	isSongServerResponse_Response()
}

type SongServerResponse_SongChunkResponse struct {
	SongChunkResponse *SongChunkResponse `protobuf:"bytes,2,opt,name=song_chunk_response,json=songChunkResponse,proto3,oneof"`
}

func (*SongServerResponse_SongChunkResponse) isSongServerResponse_Response() {}

func (m *SongServerResponse) GetResponse() isSongServerResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SongServerResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *SongServerResponse) GetSongChunkResponse() *SongChunkResponse {
	if x, ok := m.GetResponse().(*SongServerResponse_SongChunkResponse); ok {
		return x.SongChunkResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SongServerResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SongServerResponse_OneofMarshaler, _SongServerResponse_OneofUnmarshaler, _SongServerResponse_OneofSizer, []interface{}{
		(*SongServerResponse_SongChunkResponse)(nil),
	}
}

func _SongServerResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SongServerResponse)
	// response
	switch x := m.Response.(type) {
	case *SongServerResponse_SongChunkResponse:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SongChunkResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SongServerResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _SongServerResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SongServerResponse)
	switch tag {
	case 2: // response.song_chunk_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SongChunkResponse)
		err := b.DecodeMessage(msg)
		m.Response = &SongServerResponse_SongChunkResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SongServerResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SongServerResponse)
	// response
	switch x := m.Response.(type) {
	case *SongServerResponse_SongChunkResponse:
		s := proto.Size(x.SongChunkResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

//
// PeerServer messages
type PeerListRequest struct {
	SongId               int32    `protobuf:"varint,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerListRequest) Reset()         { *m = PeerListRequest{} }
func (m *PeerListRequest) String() string { return proto.CompactTextString(m) }
func (*PeerListRequest) ProtoMessage()    {}
func (*PeerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{7}
}
func (m *PeerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerListRequest.Unmarshal(m, b)
}
func (m *PeerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerListRequest.Marshal(b, m, deterministic)
}
func (dst *PeerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerListRequest.Merge(dst, src)
}
func (m *PeerListRequest) XXX_Size() int {
	return xxx_messageInfo_PeerListRequest.Size(m)
}
func (m *PeerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerListRequest proto.InternalMessageInfo

func (m *PeerListRequest) GetSongId() int32 {
	if m != nil {
		return m.SongId
	}
	return 0
}

type PeerAddRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAddRequest) Reset()         { *m = PeerAddRequest{} }
func (m *PeerAddRequest) String() string { return proto.CompactTextString(m) }
func (*PeerAddRequest) ProtoMessage()    {}
func (*PeerAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{8}
}
func (m *PeerAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAddRequest.Unmarshal(m, b)
}
func (m *PeerAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAddRequest.Marshal(b, m, deterministic)
}
func (dst *PeerAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAddRequest.Merge(dst, src)
}
func (m *PeerAddRequest) XXX_Size() int {
	return xxx_messageInfo_PeerAddRequest.Size(m)
}
func (m *PeerAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAddRequest proto.InternalMessageInfo

type PeerRemoveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerRemoveRequest) Reset()         { *m = PeerRemoveRequest{} }
func (m *PeerRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*PeerRemoveRequest) ProtoMessage()    {}
func (*PeerRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{9}
}
func (m *PeerRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerRemoveRequest.Unmarshal(m, b)
}
func (m *PeerRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerRemoveRequest.Marshal(b, m, deterministic)
}
func (dst *PeerRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerRemoveRequest.Merge(dst, src)
}
func (m *PeerRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_PeerRemoveRequest.Size(m)
}
func (m *PeerRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerRemoveRequest proto.InternalMessageInfo

type PeerServerRequest struct {
	BaseRequest *BaseRequest `protobuf:"bytes,1,opt,name=base_request,json=baseRequest,proto3" json:"base_request,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*PeerServerRequest_PeerListRequest
	//	*PeerServerRequest_PeerAddRequest
	//	*PeerServerRequest_PeerRemoveRequest
	Request              isPeerServerRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PeerServerRequest) Reset()         { *m = PeerServerRequest{} }
func (m *PeerServerRequest) String() string { return proto.CompactTextString(m) }
func (*PeerServerRequest) ProtoMessage()    {}
func (*PeerServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{10}
}
func (m *PeerServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerServerRequest.Unmarshal(m, b)
}
func (m *PeerServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerServerRequest.Marshal(b, m, deterministic)
}
func (dst *PeerServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerServerRequest.Merge(dst, src)
}
func (m *PeerServerRequest) XXX_Size() int {
	return xxx_messageInfo_PeerServerRequest.Size(m)
}
func (m *PeerServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerServerRequest proto.InternalMessageInfo

type isPeerServerRequest_Request interface {
	isPeerServerRequest_Request()
}

type PeerServerRequest_PeerListRequest struct {
	PeerListRequest *PeerListRequest `protobuf:"bytes,2,opt,name=peer_list_request,json=peerListRequest,proto3,oneof"`
}
type PeerServerRequest_PeerAddRequest struct {
	PeerAddRequest *PeerAddRequest `protobuf:"bytes,3,opt,name=peer_add_request,json=peerAddRequest,proto3,oneof"`
}
type PeerServerRequest_PeerRemoveRequest struct {
	PeerRemoveRequest *PeerRemoveRequest `protobuf:"bytes,4,opt,name=peer_remove_request,json=peerRemoveRequest,proto3,oneof"`
}

func (*PeerServerRequest_PeerListRequest) isPeerServerRequest_Request()   {}
func (*PeerServerRequest_PeerAddRequest) isPeerServerRequest_Request()    {}
func (*PeerServerRequest_PeerRemoveRequest) isPeerServerRequest_Request() {}

func (m *PeerServerRequest) GetRequest() isPeerServerRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *PeerServerRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *PeerServerRequest) GetPeerListRequest() *PeerListRequest {
	if x, ok := m.GetRequest().(*PeerServerRequest_PeerListRequest); ok {
		return x.PeerListRequest
	}
	return nil
}

func (m *PeerServerRequest) GetPeerAddRequest() *PeerAddRequest {
	if x, ok := m.GetRequest().(*PeerServerRequest_PeerAddRequest); ok {
		return x.PeerAddRequest
	}
	return nil
}

func (m *PeerServerRequest) GetPeerRemoveRequest() *PeerRemoveRequest {
	if x, ok := m.GetRequest().(*PeerServerRequest_PeerRemoveRequest); ok {
		return x.PeerRemoveRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PeerServerRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PeerServerRequest_OneofMarshaler, _PeerServerRequest_OneofUnmarshaler, _PeerServerRequest_OneofSizer, []interface{}{
		(*PeerServerRequest_PeerListRequest)(nil),
		(*PeerServerRequest_PeerAddRequest)(nil),
		(*PeerServerRequest_PeerRemoveRequest)(nil),
	}
}

func _PeerServerRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PeerServerRequest)
	// request
	switch x := m.Request.(type) {
	case *PeerServerRequest_PeerListRequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerListRequest); err != nil {
			return err
		}
	case *PeerServerRequest_PeerAddRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerAddRequest); err != nil {
			return err
		}
	case *PeerServerRequest_PeerRemoveRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerRemoveRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PeerServerRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _PeerServerRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PeerServerRequest)
	switch tag {
	case 2: // request.peer_list_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerListRequest)
		err := b.DecodeMessage(msg)
		m.Request = &PeerServerRequest_PeerListRequest{msg}
		return true, err
	case 3: // request.peer_add_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerAddRequest)
		err := b.DecodeMessage(msg)
		m.Request = &PeerServerRequest_PeerAddRequest{msg}
		return true, err
	case 4: // request.peer_remove_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerRemoveRequest)
		err := b.DecodeMessage(msg)
		m.Request = &PeerServerRequest_PeerRemoveRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PeerServerRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PeerServerRequest)
	// request
	switch x := m.Request.(type) {
	case *PeerServerRequest_PeerListRequest:
		s := proto.Size(x.PeerListRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerServerRequest_PeerAddRequest:
		s := proto.Size(x.PeerAddRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerServerRequest_PeerRemoveRequest:
		s := proto.Size(x.PeerRemoveRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PeerListResponse struct {
	SongId               int32    `protobuf:"varint,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Peers                []string `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerListResponse) Reset()         { *m = PeerListResponse{} }
func (m *PeerListResponse) String() string { return proto.CompactTextString(m) }
func (*PeerListResponse) ProtoMessage()    {}
func (*PeerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{11}
}
func (m *PeerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerListResponse.Unmarshal(m, b)
}
func (m *PeerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerListResponse.Marshal(b, m, deterministic)
}
func (dst *PeerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerListResponse.Merge(dst, src)
}
func (m *PeerListResponse) XXX_Size() int {
	return xxx_messageInfo_PeerListResponse.Size(m)
}
func (m *PeerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerListResponse proto.InternalMessageInfo

func (m *PeerListResponse) GetSongId() int32 {
	if m != nil {
		return m.SongId
	}
	return 0
}

func (m *PeerListResponse) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeerAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAddResponse) Reset()         { *m = PeerAddResponse{} }
func (m *PeerAddResponse) String() string { return proto.CompactTextString(m) }
func (*PeerAddResponse) ProtoMessage()    {}
func (*PeerAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{12}
}
func (m *PeerAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAddResponse.Unmarshal(m, b)
}
func (m *PeerAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAddResponse.Marshal(b, m, deterministic)
}
func (dst *PeerAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAddResponse.Merge(dst, src)
}
func (m *PeerAddResponse) XXX_Size() int {
	return xxx_messageInfo_PeerAddResponse.Size(m)
}
func (m *PeerAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAddResponse proto.InternalMessageInfo

type PeerRemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerRemoveResponse) Reset()         { *m = PeerRemoveResponse{} }
func (m *PeerRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*PeerRemoveResponse) ProtoMessage()    {}
func (*PeerRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{13}
}
func (m *PeerRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerRemoveResponse.Unmarshal(m, b)
}
func (m *PeerRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerRemoveResponse.Marshal(b, m, deterministic)
}
func (dst *PeerRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerRemoveResponse.Merge(dst, src)
}
func (m *PeerRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_PeerRemoveResponse.Size(m)
}
func (m *PeerRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerRemoveResponse proto.InternalMessageInfo

type PeerServerResponse struct {
	BaseResponse *BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*PeerServerResponse_PeerListResponse
	//	*PeerServerResponse_PeerAddResponse
	//	*PeerServerResponse_PeerRemoveResponse
	Response             isPeerServerResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PeerServerResponse) Reset()         { *m = PeerServerResponse{} }
func (m *PeerServerResponse) String() string { return proto.CompactTextString(m) }
func (*PeerServerResponse) ProtoMessage()    {}
func (*PeerServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_song_1db52452305abe8f, []int{14}
}
func (m *PeerServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerServerResponse.Unmarshal(m, b)
}
func (m *PeerServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerServerResponse.Marshal(b, m, deterministic)
}
func (dst *PeerServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerServerResponse.Merge(dst, src)
}
func (m *PeerServerResponse) XXX_Size() int {
	return xxx_messageInfo_PeerServerResponse.Size(m)
}
func (m *PeerServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerServerResponse proto.InternalMessageInfo

type isPeerServerResponse_Response interface {
	isPeerServerResponse_Response()
}

type PeerServerResponse_PeerListResponse struct {
	PeerListResponse *PeerListResponse `protobuf:"bytes,2,opt,name=peer_list_response,json=peerListResponse,proto3,oneof"`
}
type PeerServerResponse_PeerAddResponse struct {
	PeerAddResponse *PeerAddResponse `protobuf:"bytes,3,opt,name=peer_add_response,json=peerAddResponse,proto3,oneof"`
}
type PeerServerResponse_PeerRemoveResponse struct {
	PeerRemoveResponse *PeerRemoveResponse `protobuf:"bytes,4,opt,name=peer_remove_response,json=peerRemoveResponse,proto3,oneof"`
}

func (*PeerServerResponse_PeerListResponse) isPeerServerResponse_Response()   {}
func (*PeerServerResponse_PeerAddResponse) isPeerServerResponse_Response()    {}
func (*PeerServerResponse_PeerRemoveResponse) isPeerServerResponse_Response() {}

func (m *PeerServerResponse) GetResponse() isPeerServerResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *PeerServerResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *PeerServerResponse) GetPeerListResponse() *PeerListResponse {
	if x, ok := m.GetResponse().(*PeerServerResponse_PeerListResponse); ok {
		return x.PeerListResponse
	}
	return nil
}

func (m *PeerServerResponse) GetPeerAddResponse() *PeerAddResponse {
	if x, ok := m.GetResponse().(*PeerServerResponse_PeerAddResponse); ok {
		return x.PeerAddResponse
	}
	return nil
}

func (m *PeerServerResponse) GetPeerRemoveResponse() *PeerRemoveResponse {
	if x, ok := m.GetResponse().(*PeerServerResponse_PeerRemoveResponse); ok {
		return x.PeerRemoveResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PeerServerResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PeerServerResponse_OneofMarshaler, _PeerServerResponse_OneofUnmarshaler, _PeerServerResponse_OneofSizer, []interface{}{
		(*PeerServerResponse_PeerListResponse)(nil),
		(*PeerServerResponse_PeerAddResponse)(nil),
		(*PeerServerResponse_PeerRemoveResponse)(nil),
	}
}

func _PeerServerResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PeerServerResponse)
	// response
	switch x := m.Response.(type) {
	case *PeerServerResponse_PeerListResponse:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerListResponse); err != nil {
			return err
		}
	case *PeerServerResponse_PeerAddResponse:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerAddResponse); err != nil {
			return err
		}
	case *PeerServerResponse_PeerRemoveResponse:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerRemoveResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PeerServerResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _PeerServerResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PeerServerResponse)
	switch tag {
	case 2: // response.peer_list_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerListResponse)
		err := b.DecodeMessage(msg)
		m.Response = &PeerServerResponse_PeerListResponse{msg}
		return true, err
	case 3: // response.peer_add_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerAddResponse)
		err := b.DecodeMessage(msg)
		m.Response = &PeerServerResponse_PeerAddResponse{msg}
		return true, err
	case 4: // response.peer_remove_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerRemoveResponse)
		err := b.DecodeMessage(msg)
		m.Response = &PeerServerResponse_PeerRemoveResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PeerServerResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PeerServerResponse)
	// response
	switch x := m.Response.(type) {
	case *PeerServerResponse_PeerListResponse:
		s := proto.Size(x.PeerListResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerServerResponse_PeerAddResponse:
		s := proto.Size(x.PeerAddResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerServerResponse_PeerRemoveResponse:
		s := proto.Size(x.PeerRemoveResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "main.BaseRequest")
	proto.RegisterType((*BaseResponse)(nil), "main.BaseResponse")
	proto.RegisterType((*SongChunk)(nil), "main.SongChunk")
	proto.RegisterType((*SongChunkRequest)(nil), "main.SongChunkRequest")
	proto.RegisterType((*SongServerRequest)(nil), "main.SongServerRequest")
	proto.RegisterType((*SongChunkResponse)(nil), "main.SongChunkResponse")
	proto.RegisterType((*SongServerResponse)(nil), "main.SongServerResponse")
	proto.RegisterType((*PeerListRequest)(nil), "main.PeerListRequest")
	proto.RegisterType((*PeerAddRequest)(nil), "main.PeerAddRequest")
	proto.RegisterType((*PeerRemoveRequest)(nil), "main.PeerRemoveRequest")
	proto.RegisterType((*PeerServerRequest)(nil), "main.PeerServerRequest")
	proto.RegisterType((*PeerListResponse)(nil), "main.PeerListResponse")
	proto.RegisterType((*PeerAddResponse)(nil), "main.PeerAddResponse")
	proto.RegisterType((*PeerRemoveResponse)(nil), "main.PeerRemoveResponse")
	proto.RegisterType((*PeerServerResponse)(nil), "main.PeerServerResponse")
}

func init() { proto.RegisterFile("song.proto", fileDescriptor_song_1db52452305abe8f) }

var fileDescriptor_song_1db52452305abe8f = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xed, 0x24, 0x8d, 0x27, 0x21, 0xb1, 0xb7, 0x21, 0xb5, 0x04, 0x88, 0x68, 0x4f, 0x11,
	0x87, 0x1c, 0x00, 0x89, 0x2b, 0x4d, 0xa4, 0x2a, 0x91, 0x72, 0x40, 0xdb, 0x1b, 0x17, 0xcb, 0xa9,
	0xb7, 0xa9, 0x45, 0xfd, 0x81, 0xd7, 0x6d, 0x81, 0x7f, 0x82, 0xc4, 0x11, 0xf1, 0x0b, 0xf8, 0x81,
	0x68, 0x3f, 0xec, 0x6c, 0x36, 0x70, 0x2b, 0xb7, 0xdd, 0x37, 0x9e, 0x37, 0xf3, 0xe6, 0x8d, 0xb5,
	0x00, 0x2c, 0xcf, 0x76, 0xf3, 0xa2, 0xcc, 0xab, 0x1c, 0xb5, 0xd3, 0x28, 0xc9, 0xf0, 0x0e, 0xfa,
	0x8b, 0x88, 0x51, 0x42, 0x3f, 0xdf, 0x51, 0x56, 0xa1, 0x17, 0x00, 0xa5, 0x3c, 0x86, 0x49, 0x1c,
	0x58, 0x53, 0x6b, 0xe6, 0x12, 0x57, 0x21, 0xeb, 0x18, 0x3d, 0x03, 0xf7, 0xea, 0x36, 0xa1, 0x99,
	0x88, 0xda, 0x22, 0xda, 0x93, 0xc0, 0x3a, 0x46, 0xcf, 0xc1, 0xad, 0x92, 0x94, 0xb2, 0x2a, 0x4a,
	0x8b, 0xc0, 0x99, 0x5a, 0x33, 0x87, 0xec, 0x01, 0x7c, 0x03, 0x03, 0x59, 0x88, 0x15, 0x79, 0xc6,
	0xe8, 0x7f, 0xac, 0xf4, 0xdd, 0x02, 0xf7, 0x32, 0xcf, 0x76, 0xcb, 0x9b, 0xbb, 0xec, 0x13, 0x42,
	0xd0, 0xce, 0xa2, 0x94, 0xaa, 0x0a, 0xe2, 0x8c, 0x86, 0x60, 0x2b, 0xd6, 0x0e, 0xb1, 0x13, 0x51,
	0xac, 0x8c, 0x1e, 0xc2, 0xed, 0xd7, 0x8a, 0x32, 0xc1, 0x37, 0x20, 0xbd, 0x32, 0x7a, 0x58, 0xf0,
	0x3b, 0x7a, 0x09, 0xfd, 0x2b, 0xce, 0x14, 0x26, 0x59, 0x4c, 0xbf, 0x04, 0x6d, 0x91, 0x05, 0x02,
	0x5a, 0x73, 0x04, 0x4d, 0xa0, 0x9b, 0x5f, 0x5f, 0x33, 0x5a, 0x05, 0x1d, 0x11, 0x53, 0x37, 0x5e,
	0x99, 0x25, 0xdf, 0x68, 0xd0, 0x15, 0xa8, 0x38, 0xe3, 0x0d, 0x78, 0x4d, 0x6b, 0xf5, 0xcc, 0xcf,
	0xe0, 0x84, 0xdb, 0x12, 0x36, 0x2d, 0x75, 0xf9, 0x75, 0x1d, 0x9b, 0x95, 0x1d, 0xb3, 0x32, 0xfe,
	0x61, 0x81, 0xcf, 0xe9, 0x2e, 0x69, 0x79, 0x4f, 0xcb, 0x9a, 0xef, 0x2d, 0x0c, 0xb6, 0x11, 0xa3,
	0xa1, 0x1a, 0xa6, 0x50, 0xde, 0x7f, 0xed, 0xcf, 0xb9, 0xdf, 0x73, 0xcd, 0x6c, 0xd2, 0xdf, 0x6a,
	0xce, 0x5f, 0x00, 0x12, 0x5d, 0xc8, 0x8a, 0x75, 0xae, 0x2d, 0x72, 0x27, 0x32, 0xd7, 0xec, 0x7c,
	0xd5, 0x22, 0x1e, 0x33, 0xb0, 0x85, 0x0b, 0x27, 0x2a, 0x19, 0x2f, 0x65, 0x77, 0x2a, 0xac, 0x7c,
	0x9f, 0xcb, 0x25, 0x94, 0x75, 0x54, 0x6f, 0x23, 0x93, 0xdf, 0x6d, 0x68, 0xf1, 0x4f, 0x0b, 0x90,
	0xae, 0x51, 0xd1, 0xbc, 0x83, 0x27, 0x4a, 0xa4, 0x04, 0x14, 0x13, 0xd2, 0x55, 0xca, 0x08, 0x19,
	0x6c, 0xf5, 0xbd, 0x5b, 0xc3, 0xe9, 0x81, 0x4e, 0x95, 0x2e, 0x85, 0x9e, 0x1d, 0x09, 0x95, 0xe1,
	0x55, 0x8b, 0xf8, 0xcc, 0x04, 0x17, 0x00, 0xbd, 0x3a, 0x1f, 0xbf, 0x82, 0xd1, 0x07, 0x4a, 0xcb,
	0x4d, 0xc2, 0xaa, 0xbf, 0xf8, 0x6a, 0xe9, 0xbe, 0x62, 0x0f, 0x86, 0xfc, 0xdb, 0xf3, 0x38, 0x56,
	0x9f, 0xe2, 0x53, 0xf0, 0x39, 0x42, 0x68, 0x9a, 0xdf, 0xd7, 0x8e, 0xe0, 0x5f, 0xb6, 0x44, 0x1f,
	0xc3, 0xdd, 0x25, 0xf8, 0x05, 0xa5, 0x65, 0x78, 0x9b, 0xb0, 0xca, 0x30, 0xf7, 0xa9, 0x4c, 0x35,
	0xba, 0x5f, 0xb5, 0xc8, 0xa8, 0x30, 0x04, 0xbd, 0x07, 0x4f, 0x90, 0x44, 0x71, 0xdc, 0x70, 0x38,
	0x82, 0x63, 0xbc, 0xe7, 0xd8, 0xab, 0x5a, 0xb5, 0xc8, 0xb0, 0x38, 0x40, 0xf8, 0xf0, 0x05, 0x43,
	0x29, 0x84, 0x36, 0x24, 0x6d, 0x7d, 0xf8, 0x47, 0x83, 0xe0, 0xc3, 0x2f, 0x4c, 0x50, 0xdf, 0xb3,
	0x73, 0xf0, 0xf6, 0xdd, 0x2b, 0x9b, 0xff, 0x35, 0x7c, 0x34, 0x86, 0x0e, 0x27, 0x63, 0x81, 0x3d,
	0x75, 0x66, 0x2e, 0x91, 0x17, 0xec, 0x4b, 0xfb, 0x44, 0xab, 0xca, 0xd1, 0x31, 0x20, 0xbd, 0x15,
	0x85, 0xfe, 0xb6, 0x25, 0xfc, 0x58, 0xeb, 0x78, 0x01, 0x48, 0x37, 0xe6, 0x60, 0x1b, 0x27, 0xa6,
	0x33, 0xcd, 0x32, 0x7a, 0x85, 0xa9, 0xb7, 0x36, 0x58, 0x7a, 0xa3, 0x68, 0x1c, 0xd3, 0x60, 0x4d,
	0x5f, 0x6d, 0xb0, 0x06, 0xa1, 0x0d, 0x8c, 0x0f, 0xed, 0x51, 0x3c, 0xd2, 0x9f, 0xe0, 0xd8, 0x9f,
	0x86, 0x0a, 0x15, 0x47, 0xa8, 0xfe, 0x7b, 0x2c, 0xba, 0x1f, 0xc5, 0x73, 0xb3, 0xed, 0x8a, 0xb7,
	0xe7, 0xcd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x0e, 0xa8, 0xbc, 0x89, 0x06, 0x00, 0x00,
}
